mikeshardmind/SinbadCogs

announcer/announcer.py, crossquote/crossquote.py, embedder/embedder.py, embedder/info.json, gethelp/gethelp.py, gethelp/info.json, resourcer/info.json, resourcer/resourcer.py, serverblacklist/serverblacklist.py
Handles issue #2 
Adds embedder
=> Issue #2 Enhancements and more

suggestionbox/info.json, suggestionbox/suggestionbox.py
This is NOT feature complete yet.
Things that need to be added later:
ability to output in multiple locations.
ability to remove output locations.
=> Suggestionbox

autorooms/autorooms.py
This has yet to be tested, but adds features requested in #27
=> Added more configuration options

announcer/announcer.py
Fixes cases where the announcement channel no longer exists #38 
While also giving feedback to the owner about this.
=> Fixes for announcer (issue #38)

README.md, advstatus/advstatus.py
Adds persistence on bot restart to advstatus
=> Persistence

announcer/announcer.py
Needs an internal sanity check rather than relying on the decorator check.
Cant remove the decorator check without screwing up the help formatting from d.py
=> Added more sanity checks

autorooms/autorooms.py
* Fix prepend settings
* Fix edge case where channels were not removed
* Add Antispam to prevent intentional abuse
* Make usage easier: No longer requires a channelID (but one can still be used)
* Add Logging for aforementioned Antispam
* Restructure main logic block to be more maintainable
=> AutoRooms v5

embedmaker/embedmaker.py
adds support for embeds from yaml blocks
=> V3 embed yaml 

stickyroles/__init__.py, stickyroles/info.json, stickyroles/sticky.py
Untested, but should work in theory. If it doesn't, let me know and I'll fix it.
=> V3 stickyroles

exroles/exroles.py, exroles/info.json
Look, if you want to use it, use it, the disclaimer is provided for a reason.
=> [v3 Exroles]

exroles/exroles.py, relays/relays.py
=> [V3] relay output

rolemanagement/__init__.py, rolemanagement/converters.py, rolemanagement/events.py, rolemanagement/info.json, rolemanagement/manager.py, rolemanagement/massmanager.py, rolemanagement/utils.py
This is a WIP of the improvements coming to the role management cog. Nothing in the current iteration is guaranteed to work. (though everything as of 14cab03 should)
I'm transitioning this towards building a cog class through composition, rather than loading seperate cogs, as this will keep the help menu saner while retaining my personal requirement of logical separations for maintainability's sake.
=> [V3] RoleManagement improvements

bansync/bansync.py, bansync/converters.py
Adds support for non-bidirectional bans syncing.
This is also a stepping stone towards automatic sync but does not include this.
=> [V3 Bansync] Syndicated bans

.travis.yml, calculator/__init__.py, quotetools/helpers.py, quotetools/quotetools.py, requirements.txt
Should significantly reduce API spam
=> Quote tools, API call reduction

scheduler/checks.py, scheduler/scheduler.py
Should hide mute helpers from people who can't use
Improves a doc string for help.
=> Scheduler UX improvements

suggestionbox/core.py
=> Add reaction setting

scheduler/menus.py, scheduler/scheduler.py
=> [Scheduler] Allow canceling in menu

roomtools/converters.py, roomtools/tempchannels.py
=> [tmpc] Allow specifying a userlimit

bansync/bansync.py, embedmaker/embedmaker.py, guildblacklist/guildblacklist.py, guildwhitelist/guildwhitelist.py, macrodice/core.py, mod/__init__.py, mod/mod.py, quotetools/quotetools.py, relays/relay.py, relays/relays.py, rolemanagement/converters.py, rolemanagement/core.py, rolemanagement/massmanager.py, roomtools/__init__.py, roomtools/autorooms.py, roomtools/tempchannels.py, rss/core.py, scheduler/converters.py, scheduler/scheduler.py, screenshareautomod/core.py, suggestionbox/app_queues.py, suggestionbox/core.py
Needs a quick double check on all of this prior to merge.
Intended to make accommodating changes in 3.2 easier by removing old workarounds and cleaning up a bit in the process.
=> Cleans up some older code, doesn't refactor

roomtools/__init__.py, roomtools/tempchannels.py
Schedules a cleanup check to prevent pathological cases.
Needs testing prior to merge.
=> Roomtools cleanup extra

roomtools/__init__.py, roomtools/tempchannels.py
=> [RoomTools] Support defaulting to the current category using tmpc

rolemanagement/core.py
=> show more in roleset viewrole

.github/workflows/mypy.yml
=> Add an action for mypy

devtools/runner.py
IMO, it's convenient but I can understand you might not want it here.
=> [DevTools] Add venv's bin/Scripts folder to PATH for convenience
